name: Docker Multi-Architecture Build

on:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - master

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get hash of latest image
        id: docker-cache
        run: echo "::set-output name=hash::$(docker pull rust:alpine && docker inspect --format='{{index .RepoDigests 0}}' rust:alpine | sha1sum | head -c 40)"
      - name: cache docker cache
        uses: actions/cache@v2.1.3
        with:
          path: /tmp/dockercache
          key: ${{ runner.os }}-docker-rust-${{ steps.docker-cache.outputs.hash }}-${{ hashFiles('**/Cargo.*') }}
          restore-keys: |
            ${{ runner.os }}-docker-rust-${{ steps.docker-cache.outputs.hash }}-
            ${{ runner.os }}-docker-rust-
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: 1337kavin/libreddit:latest
          cache-from: type=local,src=/tmp/dockercache
          cache-to: type=local,dest=/tmp/dockercache
